### ISSUE TITLE
how to analyze my own .js file?

### ISSUE THREAD

**Issue by dckc** [kaist-plrg/jstar#2]
I'd like to do something like `jstar analyze myFile.js` to find arity bugs etc.

Is this supported?

**Comment by jhnaldo** [comment]
Sorry, but, JSTAR is a tool that detects type-related specification bugs in [ECMAScript specification (ECMA-262)](https://tc39.es/ecma262/) not in JavaScript programs.

**Comment by dckc** [comment]
OK... I got the impression from the debugger tool that perhaps you could apply the tool to running JavaScript programs. Does it seem feasible to extend the tool in this direction? Or does your group have any static analysis tools for JavaScript programs?

Ah... I see a diagram on https://github.com/kaist-plrg/jiset that suggests that tool is more appropriate.

**Comment by jhnaldo** [comment]
We are currently developing JSAVER, a JavaScript static analyzer, based on the JavaScript syntax and semantics extracted from [ECMAScript specification](https://tc39.es/ecma262/) via [JISET](https://github.com/kaist-plrg/jiset/issues). While the current version of JSAVER is a prototype implementation, we checked that it can successfully analyze all applicable JavaScript programs in [Test262: ECMAScript Test Suite (ECMA TR/104)](https://github.com/tc39/test262).

On the other hand, our team also has developed [SAFE](https://github.com/sukyoung/safe), a JavaScript static analyzer for [ECMAScript 5.1](https://262.ecma-international.org/5.1/), with abstract semantics designed by hand in several years.

**Comment by dckc** [comment]
ah. now I understand. Thank you!
